version: "3.9"

services:
  api:
    build: .
    container_name: flight_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: flight_streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    restart: unless-stopped
